In [ ]:
# Creating empty array :

In [1]:
import numpy as np

In [2]:
array_empty = np.empty((2,3))

array_empty

array([[1.47e-321, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [ ]:
# Identity Matrix in Numpy:

In [3]:
array_eye = np.eye(4)

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# I want to print the numbers in array till 20:

#Arrange (startvalue, stopvalue,stepcount)

In [4]:
x = np.arange(20) # last value is always exclusive

x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# I Want to print even numbers till 20:

In [5]:
array_of_evens = np.arange(2,20,2)

array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
array_of_Floats = np.arange(0,3,0.3)

array_of_Floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [ ]:
# DIMENSIONS IN ARRAY

In [ ]:
# X---------------> 1D Array
# (X,y)---------------> 2D Array
# (X,y,z)---------------> 3D Array

In [7]:
array_2d = np.array([(2,3,4),(5,6,7)])

array_2d

array([[2, 3, 4],
       [5, 6, 7]])

In [8]:
array_2d.shape #(x,y)

(2, 3)

In [11]:
array_2d.ndim #(x,y)

2

In [17]:
# int que :shape VS ndim

# Using the reshape to create n dimensional array

In [18]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [14]:
x = np.arange(6).reshape(3,2) # reshape 3*2 =6
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
y = np.arange(9)
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
z = np.arange(6)
z = np.arange(6).reshape(4,3)
z

ValueError: cannot reshape array of size 6 into shape (4,3)