In [1]:
pip install numpy

In [ ]:
#Creating an array from a regular python:

In [1]:
import numpy as np


In [2]:
arrays_one = np.array([1,2,3,4,5])

arrays_one

array([1, 2, 3, 4, 5])

In [3]:
type(arrays_one)

numpy.ndarray

In [4]:
numbers = [9,8,7,6]

In [5]:
array_two = np.array(numbers)

In [6]:
array_two

array([9, 8, 7, 6])

In [7]:
type(array_two)

numpy.ndarray

In [ ]:
# Difference between array and List?

In [ ]:
# creating an array of zeros with desire shape(x,y):
# x----->no of rows
# y----->no of columns

In [8]:
array_of_zeros = np.zeros((3,4)) #(x,y)

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
type(array_of_zeros)

numpy.ndarray

In [ ]:
# creating an array of ones with desire shape(x,y):

In [10]:
array_of_ones = np.ones((4,5))  #(x,y)

array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
type(array_of_ones)

numpy.ndarray

In [12]:
array_of_ones_int = np.ones((4,5),dtype = np.int16) # int16 int32 int64

array_of_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)