In [2]:
# Arithimetic operations in Array

import numpy as np

In [3]:
a = np.array([10,10,10])

In [4]:
b = np.array([5,5,5])

In [5]:
a+b

array([15, 15, 15])

In [6]:
a-b

array([5, 5, 5])

In [7]:
a*b

array([50, 50, 50])

In [8]:
a/b

array([2., 2., 2.])

In [9]:
a%3

array([1, 1, 1], dtype=int32)

In [10]:
a > 25

array([False, False, False])

In [11]:
a< 25

array([ True,  True,  True])

In [ ]:
# modifying an existing array rather than creating a new one:

In [18]:
a*=3
a

array([90, 90, 90])

In [19]:
b+=a

In [20]:
b

array([115, 115, 115])

In [21]:
a

array([90, 90, 90])

In [ ]:
# UNINARY Operator

In [23]:
ages = np.array([12,15,18,20])

In [24]:
ages

array([12, 15, 18, 20])

In [ ]:
# I want to know the total sum of the array:

In [25]:
ages.sum()

65

In [26]:
ages.min()

12

In [27]:
ages.max()

20